version: "3"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - 80:80

  server:
    build: ./server
    container_name: server
    ports:
      - 5000:5000
    # We can pass env from here if not then it will take the default
    environment:
      - KEY_FILE=/usr/src/app/application_default_credentials.json
    #   - TOKEN_EXPIRY=30m
    #   - TOKEN_KEY=$@mp1e
    #   - SALT_ROUND=10
